import {Nunito} from 'next/font/google'
import ClientOnly from './components/ClientOnly'
import Modal from './components/modals/Modals'
import Navbar from './components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <ClientOnly>
        <Modal isOpen title='Login Here' />
        <Navbar />
      </ClientOnly>
        {children}</body>
    </html>
  )
}
